/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazcore;

import core.ExecuterComponent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import logica.SettingDataType;

/**
 *
 * @author dark
 */
public class ExecuteComponent extends javax.swing.JPanel implements TableModelListener {

    private ArrayList<jpComponenteParametro> parametros;

    /**
     * Creates new form ExecuteComponent
     */
    public ExecuteComponent() {
        initComponents();
        parametros = new ArrayList<>();
        loadParameter();
        Object[][] data = new Object[0][2];
        String[] head = {"indice", "Nombre"};
        updateTable(head, data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelParametros = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtResultados = new javax.swing.JTable();
        btnEjecutar = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();

        panelParametros.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(panelParametros);

        jtResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtResultados);

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        lbTitle.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(543, 543, 543))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEjecutar)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        // TODO add your handling code here:
        if(validarParametros()){
            try {
                String ruta = "/home/dark/NetBeansProjects/InterfazCore/src/configuracion/ModuloFuncional2.jar";
                ArrayList<String> parametros = new ArrayList<>();
                for(jpComponenteParametro component_parameter: this.parametros){
                    parametros.add(component_parameter.getValue());
                }
                ExecuterComponent exec =new ExecuterComponent();
                ExecuterComponent.ResponseExecuter response = exec.executeJar(ruta, parametros, 2);
                if(response.isValido()){
                    String[] head = {"indice", "Nombre"};
                    updateTable(head, response.getData());
                }else{
                    JOptionPane.showMessageDialog(this, response.getMensage(), "Ejecutar componente", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(ExecuteComponent.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_btnEjecutarActionPerformed

    public boolean validarParametros() {
        break_parameter:
        for (jpComponenteParametro parameter : this.getParametros()) {
            if (parameter.getValue() == "" || parameter.getValue() == null) {
                JOptionPane.showMessageDialog(this, "El atributo "+parameter.getNameParameter() +" es requerido.", "Ejecutar componenete", JOptionPane.INFORMATION_MESSAGE);
                parameter.requestFocusInWindow();
                return false;
            }
        }
        return true;
    }

    public ArrayList<jpComponenteParametro> getParametros() {
        return parametros;
    }

    public void loadParameter() {
        jpComponenteParametro parametro = new jpComponenteParametro(0, SettingDataType.STRING, "Descripcion");
        panelParametros.add(parametro);
        jpComponenteParametro parametro1 = new jpComponenteParametro(1, SettingDataType.INTEGER, "Numero");
        panelParametros.add(parametro1);
        jpComponenteParametro parametro2 = new jpComponenteParametro(2, SettingDataType.FLOAT, "Real");
        panelParametros.add(parametro2);
        panelParametros.updateUI();
        System.out.println("*----------------------------------> " + this.getParametros() );
        this.getParametros().add(parametro);
        this.getParametros().add(parametro1);
        this.getParametros().add(parametro2);
    }

    public void updateTable(String[] head, Object[][] body) {
        jtResultados.setModel(new DefaultTableModel(body, head) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return getValueAt(0, columnIndex).getClass();
            }
        });

        jtResultados.getModel().addTableModelListener(this);
        jtResultados.setRowHeight(20);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtResultados;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel panelParametros;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tableChanged(TableModelEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
